loading app /home/jakob/ovs-sgx/SDN_Controller/learning_switch.py
loading app ryu.controller.ofp_handler
instantiating app /home/jakob/ovs-sgx/SDN_Controller/learning_switch.py of SimpleSwitch
instantiating app ryu.controller.ofp_handler of OFPHandler
BRICK SimpleSwitch
  CONSUMES EventOFPPacketIn
  CONSUMES EventOFPPortStatus
BRICK ofp_event
  PROVIDES EventOFPPacketIn TO {'SimpleSwitch': set(['main'])}
  PROVIDES EventOFPPortStatus TO {'SimpleSwitch': set(['main'])}
  CONSUMES EventOFPSwitchFeatures
  CONSUMES EventOFPErrorMsg
  CONSUMES EventOFPEchoRequest
  CONSUMES EventOFPEchoReply
  CONSUMES EventOFPPortDescStatsReply
  CONSUMES EventOFPHello
  CONSUMES EventOFPPortStatus
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py", line 59, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py", line 131, in wrap_and_handle
    handle(ssl.wrap_socket(sock, **ssl_args), addr)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 369, in wrap_socket
    return GreenSSLSocket(sock, *a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 64, in __init__
    ca_certs, do_handshake_on_connect and six.PY2, *args, **kw)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 260, in do_handshake
    super(GreenSSLSocket, self).do_handshake)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 109, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)

hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py", line 59, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py", line 131, in wrap_and_handle
    handle(ssl.wrap_socket(sock, **ssl_args), addr)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 369, in wrap_socket
    return GreenSSLSocket(sock, *a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 64, in __init__
    ca_certs, do_handshake_on_connect and six.PY2, *args, **kw)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 260, in do_handshake
    super(GreenSSLSocket, self).do_handshake)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/green/ssl.py", line 109, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)

